/**
 * kconfig_parser.js - Linux .config Deserializer & Serializer.
 */

export class KconfigParser {
  /**
   * Parse a raw Linux .config string into key-value assignments.
   */
  static parse(content) {
    const assignments = {};
    const lines = (content || "").split(/\r?\n/);

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      // Handle '# CONFIG_XXX is not set'
      const unsetMatch = trimmed.match(/^#\s*(CONFIG_\w+)\s+is not set/);
      if (unsetMatch) {
        assignments[unsetMatch[1]] = "n";
        continue;
      }

      if (trimmed.startsWith("#")) continue;

      // Handle 'CONFIG_XXX=y', 'CONFIG_XXX=m', 'CONFIG_XXX="val"', 'CONFIG_XXX=123'
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx > 0) {
        const key = trimmed.substring(0, eqIdx).trim();
        let val = trimmed.substring(eqIdx + 1).trim();

        if (val.startsWith('"') && val.endsWith('"')) {
          val = val.substring(1, val.length - 1);
        }

        assignments[key] = val;
      }
    }

    return assignments;
  }

  /**
   * Serialize symbol assignments into standard Linux .config format.
   */
  static serialize(assignments, version = "v3.0", arch = "x86") {
    const lines = [
      "#",
      `# Automatically generated by KernelInfo Developer IDE for Linux ${version} (${arch})`,
      "#",
      ""
    ];

    const seen = new Set();
    const sortedKeys = Object.keys(assignments || {}).sort();

    for (const key of sortedKeys) {
      const bare = key.startsWith("CONFIG_") ? key.substring(7) : key;
      if (seen.has(bare)) continue;
      seen.add(bare);

      const fullKey = `CONFIG_${bare}`;
      const val = assignments[key];

      if (val === "n" || val === false) {
        lines.push(`# ${fullKey} is not set`);
      } else if (val === "y" || val === "m") {
        lines.push(`${fullKey}=${val}`);
      } else if (typeof val === "number" || /^\d+$/.test(val)) {
        lines.push(`${fullKey}=${val}`);
      } else {
        lines.push(`${fullKey}="${val}"`);
      }
    }

    lines.push("");
    return lines.join("\n");
  }
}
