"""GreatProcessor.py - Global State Container & IPC Multiprocessing Manager.

===============================================================================
GREAT PROCESSOR ARCHITECTURAL GUIDE
===============================================================================
This module defines `GreatProcessor` (`gp`), the central runtime state container
for the parser engine. `gp` manages version state, table schema registries, git diff
change lists, and cross-process IPC communication during multicore parsing.

1. RUNTIME STATE ATTRIBUTES:
-------------------------------------------------------------------------------
  - `PURGE_LIST`: List of temporary working directories on RAMDISK scheduled for cleanup.
  - `Table_Array`: Registered `Table` schema objects indexed by `table_id`.
  - `Version_Name`: Active git release tag/branch string. Initialized to empty git tree hash
    (`4b825dc642cb6eb9a060e54bf8d69288fbee4904`) for initial import baseline.
  - `Old_Version_Name`: Prior release tag string.
  - `VID` / `Old_VID`: Integer primary key IDs corresponding to active and prior versions in `m_v_main`.
  - `Change_List`: Raw git diff status lines generated by `MasterFile.generate_change_list()`.
  - `ChangeSet_Dict`: Dictionary mapping relative file path strings to their parsed `ChangeSet` objects (`{file_path: CS}`).

2. MULTIPROCESSING IPC MECHANICS (`start_manager`, `push_set_to_main`, `stop_manager`):
-------------------------------------------------------------------------------
  - Worker processes run isolated `file_processing()` workers.
  - Each worker populates its local `gp.ChangeSet_Dict`, invokes `CS.clear_bloat()` to remove
    un-picklable references (`gp`, `mf`, `debug`), and calls `push_set_to_main()`.
  - `push_set_to_main()` serializes the local dictionary via `pickle.dumps()` and appends it to
    the shared IPC list (`Shared_ChangeSet_Dict_List`).
  - `stop_manager()` executes on the main process to deserialize (`pickle.loads()`) and merge
    all worker dictionaries into `gp.ChangeSet_Dict`, then safely terminates the manager.
===============================================================================
"""
import multiprocessing
import pickle
from TableHandling import ChangeSet

class GreatProcessor:
    """Central runtime state container (`gp`) and multiprocessing IPC manager."""

    def __init__(self) -> None:
        """Initialize version state tracking, table array, and manager attributes."""
        self.PURGE_LIST = []
        self.Table_Array = []
        self.Version_Name = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
        self.Old_Version_Name = 0
        self.VID = 0
        self.Old_VID = 0
        self.Change_List = None
        self.ChangeSet_Dict = {}
        self.Alt_ChangeSet_Dict = {}
        self.Manager = None
        self.Shared_ChangeSet_Dict_List = None

    def push_set_to_main(self) -> None:
        """Serialize worker process `ChangeSet_Dict` via `pickle.dumps()` and push to IPC shared list."""
        self.Shared_ChangeSet_Dict_List.append(pickle.dumps(self.ChangeSet_Dict))
        return

    def safe_get_cs(self, path: str):
      CS = self.ChangeSet_Dict.get(path)
      if CS is None:
        CS = self.Alt_ChangeSet_Dict.get(path)
        if CS is None:
          CS = ChangeSet("M", path)
          self.Alt_ChangeSet_Dict[path] = CS
          CS.parse()
      return CS

    def start_manager(self) -> None:
        """Initialize `multiprocessing.Manager()` and create `Shared_ChangeSet_Dict_List` for worker IPC."""
        self.Manager = multiprocessing.Manager()
        self.Shared_ChangeSet_Dict_List = self.Manager.list()
        return

    def stop_manager(self) -> None:
        """Deserialize pickled worker ChangeSet dictionaries, merge into `gp.ChangeSet_Dict`, and shut down manager."""
        for shared in self.Shared_ChangeSet_Dict_List:
            self.ChangeSet_Dict.update(pickle.loads(shared))  # noqa: S301

        del self.Manager
        del self.Shared_ChangeSet_Dict_List
        self.Manager = None
        self.Shared_ChangeSet_Dict_List = []
        return

    def reset_cs(self) -> None:
        """Reset `Change_List` and `ChangeSet_Dict` upon completion of a version parsing pass."""
        del self.Alt_ChangeSet_Dict
        self.Alt_ChangeSet_Dict = self.ChangeSet_Dict
        del self.Change_List
        del self.ChangeSet_Dict
        self.Change_List = None
        
        self.ChangeSet_Dict = {}
        
        return
