"""parser/c_ast - Next-Generation High-Speed C & Assembly AST Parser Subsystem.

Authoritative specification: See parser/c_ast/CAST_API.md for complete API,
architecture, and state contract specifications.
"""
from __future__ import annotations

from parser.c_ast.ctypes_bindings import (
    AST_KIND,
    _CLANG_GET_EXTENT,
    _CLANG_GET_CURSOR_EXTENT,
    _CLANG_GET_RANGE_START,
    _CLANG_GET_RANGE_END,
    _CLANG_GET_SPELLING_LOC,
    _CLANG_GET_TOKEN_KIND,
    _CLANG_TOKEN_KIND_MAP,
    _CTYPES_F_PTR,
    _CTYPES_S_LINE,
    _CTYPES_S_COL,
    _CTYPES_S_OFF,
    _CTYPES_E_LINE,
    _CTYPES_E_COL,
    _CTYPES_E_OFF,
    _CTYPES_BYREF,
    _BYREF_F_PTR,
    _BYREF_S_LINE,
    _BYREF_S_COL,
    _BYREF_S_OFF,
    _BYREF_E_LINE,
    _BYREF_E_COL,
    _BYREF_E_OFF,
    safe_spelling,
    safe_cursor_spelling,
)

from parser.c_ast.tokenizer import (
    Line,
    get_cursor_line,
    TokenStream,
    ParsedToken,
)

from parser.c_ast.ast_nodes import (
    Ast,
    End_Mode,
    Zone_Type,
    CQual,
    TypeToken,
    TypeSegment,
    TSRef,
    get_notbind_type,
    Ast_Comment,
    Ast_ASM_Directive,
    Ast_ASM_Macro,
    Ast_ASM_Instruction,
    Ast_ASM_Label,
    Ast_ASM_Comment,
    CPPro,
    CPPro_if,
    CPPro_elif,
    CPPro_else,
    CPPro_endif,
    CPPro_ifdef,
    CPPro_ifndef,
    CPPro_elifdef,
    CPPro_elifndef,
    CPPro_define,
    CPPro_undef,
    CPPro_include,
    CPPro_embed,
    CPPro_line,
    CPPro_error,
    CPPro_warning,
    CPPro_pragma,
    CPPro_defined,
    Ast_CallExpr,
    Ast_MemberRefExpr,
    Ast_DeclRefExpr,
    Ast_MacroRefExpr,
    Ast_MACRO_INSTANTIATION,
)

from parser.c_ast.cursor_tree import (
    Ast_Statement,
    Ast_CompoundStmt,
    Ast_IfStmt,
    Ast_ReturnStmt,
    Ast_WhileStmt,
    Ast_ForStmt,
    Ast_DoStmt,
    Ast_SwitchStmt,
    Ast_CaseStmt,
    Ast_DefaultStmt,
    Ast_BreakStmt,
    Ast_ContinueStmt,
    Ast_GotoStmt,
    Ast_AsmStmt,
    Ast_LabelStmt,
    Ast_BinaryOperator,
    Ast_UnaryOperator,
    Ast_Expression,
    AST_Array,
    AST_Initializer,
    AST_Enum_Equal,
    Zone,
    C_Type,
    SemanticPartitioner,
    resolve_cppro_scopes,
    resolve_cursor_type_ast,
    get_decl_type,
)

from parser.c_ast.tag_tracker import (
    get_prior_tags,
    close_prior_tags,
    match_prior_tag_transition,
    check_exact_match,
)

from parser.c_ast.cs_extractor import (
    CSExtractor,
)

from parser.c_ast.c_ast import (
    c_ast_parse,
    process_c_ast,
    TokenList,
    Ast_Manager,
    comment_remover,
)

__all__ = [
    "c_ast_parse",
    "process_c_ast",
    "Ast_Manager",
    "TokenList",
    "TokenStream",
    "ParsedToken",
    "Line",
    "get_cursor_line",
    "get_prior_tags",
    "close_prior_tags",
    "match_prior_tag_transition",
    "check_exact_match",
    "Ast",
    "Zone",
    "Zone_Type",
    "C_Type",
    "SemanticPartitioner",
    "CSExtractor",
    "resolve_cppro_scopes",
    "resolve_cursor_type_ast",
    "get_decl_type",
    "get_notbind_type",
    "CQual",
    "TypeToken",
    "TypeSegment",
    "TSRef",
    "End_Mode",
    "AST_KIND",
    "safe_spelling",
    "safe_cursor_spelling",
    "comment_remover",
    "Ast_Comment",
    "Ast_ASM_Directive",
    "Ast_ASM_Macro",
    "Ast_ASM_Instruction",
    "Ast_ASM_Label",
    "Ast_ASM_Comment",
    "CPPro",
    "CPPro_if",
    "CPPro_elif",
    "CPPro_else",
    "CPPro_endif",
    "CPPro_ifdef",
    "CPPro_ifndef",
    "CPPro_elifdef",
    "CPPro_elifndef",
    "CPPro_define",
    "CPPro_undef",
    "CPPro_include",
    "CPPro_embed",
    "CPPro_line",
    "CPPro_error",
    "CPPro_warning",
    "CPPro_pragma",
    "CPPro_defined",
    "Ast_Statement",
    "Ast_CompoundStmt",
    "Ast_IfStmt",
    "Ast_ReturnStmt",
    "Ast_WhileStmt",
    "Ast_ForStmt",
    "Ast_DoStmt",
    "Ast_SwitchStmt",
    "Ast_CaseStmt",
    "Ast_DefaultStmt",
    "Ast_BreakStmt",
    "Ast_ContinueStmt",
    "Ast_GotoStmt",
    "Ast_LabelStmt",
    "Ast_AsmStmt",
    "Ast_Expression",
    "AST_Array",
    "AST_Initializer",
    "AST_Enum_Equal",
    "Ast_CallExpr",
    "Ast_MemberRefExpr",
    "Ast_DeclRefExpr",
    "Ast_MacroRefExpr",
    "Ast_BinaryOperator",
    "Ast_UnaryOperator",
    "Ast_MACRO_INSTANTIATION",
    "_CLANG_GET_EXTENT",
    "_CLANG_GET_RANGE_START",
    "_CLANG_GET_RANGE_END",
    "_CLANG_GET_SPELLING_LOC",
]
