"""GreatProcessor.py - Global State Container & IPC Multiprocessing Manager.

===============================================================================
GREAT PROCESSOR ARCHITECTURAL GUIDE
===============================================================================
This module defines `GreatProcessor` (`gp`), the central runtime state container
for the parser engine. `gp` manages version state, table schema registries, git diff
change lists, and cross-process IPC communication during multicore parsing.

1. RUNTIME STATE ATTRIBUTES:
-------------------------------------------------------------------------------
  - `PURGE_LIST`: List of temporary working directories on RAMDISK scheduled for cleanup.
  - `Table_Array`: Registered `Table` schema objects indexed by `table_id`.
  - `Version_Name`: Active git release tag/branch string. Initialized to empty git tree hash
    (`4b825dc642cb6eb9a060e54bf8d69288fbee4904`) for initial import baseline.
  - `Old_Version_Name`: Prior release tag string.
  - `VID` / `Old_VID`: Integer primary key IDs corresponding to active and prior versions in `m_v_main`.
  - `Change_List`: Raw git diff status lines generated by `MasterFile.generate_change_list()`.
  - `ChangeSet_Dict`: Dictionary mapping relative file path strings to their parsed `ChangeSet` objects (`{file_path: CS}`).

2. MULTIPROCESSING IPC MECHANICS (`start_manager`, `push_set_to_main`, `stop_manager`):
-------------------------------------------------------------------------------
  - Worker processes run isolated `file_processing()` workers.
  - Each worker populates its local `gp.ChangeSet_Dict`, invokes `CS.clear_bloat()` to remove
    un-picklable references (`gp`, `mf`, `debug`), and calls `push_set_to_main()`.
  - `push_set_to_main()` serializes the local dictionary via `pickle.dumps()` and appends it to
    the shared IPC list (`Shared_ChangeSet_Dict_List`).
  - `stop_manager()` executes on the main process to deserialize (`pickle.loads()`) and merge
    all worker dictionaries into `gp.ChangeSet_Dict`, then safely terminates the manager.
===============================================================================
"""
import multiprocessing
import pickle
import zlib
from collections import OrderedDict
from typing import Any
from core.TableHandling import ChangeSet


class CompressedChangeSetDict(dict):
    """Memory-optimized dictionary that compresses ChangeSet objects in RAM.

    Maintains a small LRU cache in decompressed memory, while keeping all other
    queued ChangeSets as compact zlib byte buffers.
    """

    def __init__(self, lru_cache_size: int = 50, *args: Any, **kwargs: Any) -> None:
        super().__init__()
        self._compressed_store: dict[str, bytes | None] = {}
        self._lru_cache: OrderedDict[str, Any] = OrderedDict()
        self._lru_size = lru_cache_size
        if args or kwargs:
            self.update(*args, **kwargs)

    def _evict_lru(self) -> None:
        """Evict oldest entries from LRU cache and re-compress to persist any in-place mutations."""
        while len(self._lru_cache) > self._lru_size:
            k, v = self._lru_cache.popitem(last=False)
            if v is not None and k in self._compressed_store:
                try:
                    raw_bytes = pickle.dumps(v, protocol=pickle.HIGHEST_PROTOCOL)
                    self._compressed_store[k] = zlib.compress(raw_bytes, level=1)
                except Exception:
                    pass

    def __setitem__(self, key: str, value: Any) -> None:
        if value is None:
            self._compressed_store[key] = None
            self._lru_cache.pop(key, None)
            return

        # Compress into a single flat byte buffer
        raw_bytes = pickle.dumps(value, protocol=pickle.HIGHEST_PROTOCOL)
        self._compressed_store[key] = zlib.compress(raw_bytes, level=1)

        # Keep in local LRU working cache
        self._lru_cache[key] = value
        self._lru_cache.move_to_end(key)
        self._evict_lru()

    def __getitem__(self, key: str) -> Any:
        if key in self._lru_cache:
            self._lru_cache.move_to_end(key)
            return self._lru_cache[key]

        if key not in self._compressed_store:
            raise KeyError(key)

        compressed = self._compressed_store[key]
        if compressed is None:
            return None

        # Decompress on-demand
        obj = pickle.loads(zlib.decompress(compressed))  # noqa: S301
        self._lru_cache[key] = obj
        self._lru_cache.move_to_end(key)
        self._evict_lru()
        return obj

    def __delitem__(self, key: str) -> None:
        del self._compressed_store[key]
        self._lru_cache.pop(key, None)

    def __contains__(self, key: object) -> bool:
        return key in self._compressed_store

    def __len__(self) -> int:
        return len(self._compressed_store)

    def __iter__(self):
        return iter(self._compressed_store)

    def get(self, key: str, default: Any = None) -> Any:
        if key in self._lru_cache:
            self._lru_cache.move_to_end(key)
            return self._lru_cache[key]

        if key not in self._compressed_store:
            return default

        compressed = self._compressed_store[key]
        if compressed is None:
            return None

        obj = pickle.loads(zlib.decompress(compressed))  # noqa: S301
        self._lru_cache[key] = obj
        self._lru_cache.move_to_end(key)
        self._evict_lru()
        return obj

    def keys(self):
        return self._compressed_store.keys()

    def values(self):
        for k in self.keys():
            yield self[k]

    def items(self):
        for k in self.keys():
            yield (k, self[k])

    def update(self, *args: Any, **kwargs: Any) -> None:
        if args:
            other = args[0]
            if isinstance(other, dict):
                for k, v in other.items():
                    self[k] = v
            else:
                for k, v in other:
                    self[k] = v
        for k, v in kwargs.items():
            self[k] = v

    def pop(self, key: str, *args: Any) -> Any:
        if key in self:
            val = self[key]
            del self[key]
            return val
        if args:
            return args[0]
        raise KeyError(key)

    def clear(self) -> None:
        self._compressed_store.clear()
        self._lru_cache.clear()

    def __bool__(self) -> bool:
        return bool(self._compressed_store)


class GreatProcessor:
    """Central runtime state container (`gp`) and multiprocessing IPC manager."""

    def __init__(self) -> None:
        """Initialize version state tracking, table array, and manager attributes."""
        self.PURGE_LIST = []
        self.Table_Array = []
        self.Version_Name = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
        self.Old_Version_Name = 0
        self.VID = 0
        self.Old_VID = 0
        self.Change_List = None
        self.ChangeSet_Dict = {}
        self.Alt_ChangeSet_Dict = {}
        self.Manager = None
        self.Shared_ChangeSet_Dict_List = None

    def init_cs_dict(self) -> None:
        """Initialize or reset ChangeSet_Dict according to active G.LOW_MEMORY_MODE."""
        from core.globalstuff import G
        if G.VERY_LOW_MEMORY_MODE:
            self.ChangeSet_Dict = CompressedChangeSetDict(lru_cache_size=25)
            self.Alt_ChangeSet_Dict = CompressedChangeSetDict(lru_cache_size=25)
        elif G.LOW_MEMORY_MODE:
            self.ChangeSet_Dict = CompressedChangeSetDict(lru_cache_size=50)
            self.Alt_ChangeSet_Dict = CompressedChangeSetDict(lru_cache_size=50)
        else:
            self.ChangeSet_Dict = {}
            self.Alt_ChangeSet_Dict = {}

    def push_set_to_main(self) -> None:
        """Serialize worker process `ChangeSet_Dict` via `pickle.dumps()` and push to IPC shared list."""
        self.Shared_ChangeSet_Dict_List.append(pickle.dumps(self.ChangeSet_Dict))
        return

    # this is not optimized as reset_cs destroys our progress... might be too much to ask to keep 2 CS_list
    def safe_get_cs(self, path: str):
        CS = self.ChangeSet_Dict.get(path)
        if CS is None:
            CS = self.Alt_ChangeSet_Dict.get(path)
            if CS is None:
                CS = ChangeSet("M", path)
                self.Alt_ChangeSet_Dict[path] = CS
                CS.parse()
        return CS

    def start_manager(self) -> None:
        """Initialize `Shared_ChangeSet_Dict_List` for worker IPC."""
        self.Shared_ChangeSet_Dict_List = []
        return

    def stop_manager(self) -> None:
        """Deserialize pickled worker ChangeSet dictionaries and merge into `gp.ChangeSet_Dict`."""
        if self.Shared_ChangeSet_Dict_List:
            for shared in self.Shared_ChangeSet_Dict_List:
                self.ChangeSet_Dict.update(pickle.loads(shared))  # noqa: S301
        self.Shared_ChangeSet_Dict_List = []
        return

    def reset_cs(self) -> None:
        """Reset Change_List and ChangeSet_Dict upon completion of a version parsing pass."""
        self.Alt_ChangeSet_Dict.clear()
        self.Change_List = None
        self.ChangeSet_Dict.clear()
        return
